apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-upgrade-25-27-05-gitc
spec:
  title: "Lab: Get the application to fully compile"
  description: "Using the SCAR method work iteratively until the application successfully compiles again"
  workshop:
    image: jdk8-environment:*
    packages:
      - name: spring-academy-lab
        files:
          - image:
              url: ghcr.io/spring-academy/spring-academy-extension-packages/spring-academy-lab
              tagSelection:
                semver:
                  constraints: ">=1.0.0 <2.0.0"
    files:
      - image: # Note: format is {repository-name}-files
          url: $(image_repository)/course-spring-boot-2-5-to-2-7-upgrade-files:$(workshop_version)
        includePaths:
          - /workshops/05-gitc/workshop/**
        newRootPath: workshops/05-gitc
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/course-spring-boot-2-5-to-2-7-upgrade-code
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LESSON_LABEL
        value: 05-gitc-start
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: true
    dashboards:
      - name: Editor
      - name: Terminal
